# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -o bartering

    - name: Get commit SHA
      id: commit_sha
      run: echo "::set-output name=SHA::$(git rev-parse --short HEAD)"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: v1.0.0-${{ steps.commit_sha.outputs.SHA }}
        release_name: Release-${{ steps.commit_sha.outputs.SHA }}
        body: |
          Changes in this release:
          - Describe your changes here
        draft: false
        prerelease: false
        files: bartering
